### ISSUE TITLE
Double-tap to zoom in/out of CCLayerPanZoom?

### ISSUE THREAD

**Issue by horatio-sans-serif** [cocos2d/cocos2d-iphone-extensions#110]
I haven't played with this yet but have just looked over the API. I don't see any support for double-tap to zoom in/out of a CCLayerPanZoom. 

I guess it's possible to set panBoundsRect when the delegate's when layerPanZoom:clickedAtPoint:tapCount: is called to achieve this? I haven't tried yet.

**Comment by psineur** [comment]
Yeah, it's possible to use -layerPanZoom:clicletAtPoint:tapCount: for this, but don't change the panBoundsRect - it's about content, not the zoom.
Just adjust the scale of the PanZoomLayer - probably it will look better with fast CCScaleTo action.

09.05.2012, в 23:08, Brian Hammond написал(а):

**Comment by horatio-sans-serif** [comment]
Thanks, that worked fine. 

I mentioned panBoundsRect as a potential way to center the zoom layer around the double-tapped point. I've been playing with a few things dealing with anchorPoint and separately CCMoveBy/To but I can't seem to figure out how to move it the right way... Thoughts?

Consider the Maps app and its behavior of double taps to zoom in. Alas, it does not center around the tap point while zooming but seems to zoom _towards_ the tap point at least. That's what I would like to replicate.

**Comment by horatio-sans-serif** [comment]
This **sort of** does what I want but it's not there 100% ...
https://gist.github.com/2648522

**Comment by alexeylang** [comment]
Hello, fictorial! I'm author of CCLayerPanZoom. I rewrote part of your code (you forgot about anchorPoint). Try to use it:

```
- (void) layerPanZoom: (CCLayerPanZoom *) sender 
       clickedAtPoint: (CGPoint) point
             tapCount: (NSUInteger) tapCount
{
    NSLog(@"CCLayerPanZoomTestLayer#layerPanZoom: %@ clickedAtPoint: { %f, %f }", sender, point.x, point.y);

    if (tapCount == 2) 
    {
        float midScale = (sender.minScale + sender.maxScale) / 2.0;
        float newScale = (sender.scale <= midScale) ? sender.maxScale : sender.minScale;

        CGFloat deltaX = (point.x - sender.anchorPoint.x * sender.contentSize.width) * (newScale - sender.scale);
        CGFloat deltaY = (point.y - sender.anchorPoint.y * sender.contentSize.height) * (newScale - sender.scale);
        CGPoint position = ccp(sender.position.x - deltaX, sender.position.y - deltaY);

        [sender runAction: [CCSpawn actions: 
                            [CCScaleTo actionWithDuration:0.4 scale:newScale], 
                            [CCMoveTo actionWithDuration:0.4 position:position], 
                            nil]];
    }
}
```

**Comment by horatio-sans-serif** [comment]
Aha! Thanks. I knew I was missing something obvious. That's what I get for trying this on 2-hours of sleep!

**Comment by dmquan** [comment]
Hi All,

I'm a newbie used cocos2dx on Android. I don't know how to use your code,is this Object C code ? Please help me ! Thanks.
