### ISSUE TITLE
Use of undeclared identifier 'CC_GL_BLEND'

### ISSUE THREAD

**Issue by oddjobbodgod** [cocos2d/cocos2d-iphone-extensions#119]
When importing the CCScrollLayer.m and respective .h and incorporate them into my app, on compiling I get the error 'Use of undeclared identifier 'CC_GL_BLEND'. Using cocos2d-iphone-2.1-beta2.

**Comment by ricardoquesada** [comment]
Thanks. fixed in develop-v2 branch
