### ISSUE TITLE
CCBigImage not working when layer is scaled

### ISSUE THREAD

**Issue by jamiefearon** [cocos2d/cocos2d-iphone-extensions#47]
I propose fixing CCBigImage to work correctly at different scales. CCBigImage is a very good solution to provide a background to your game world. As well as panning many games require zooming in and out of the world. This is generally done by scaling the world layer. 

I see CCBigImage working at different scales as an essential component.

**Comment by psineur** [comment]
This is fixed in the develop branch and will be released in 0.1.2
Feel free to try develop branch version and close this issue if it works good for you, or provide additional feedback and requests in comments and leave this issue open.
