### ISSUE TITLE
compression warning with no rotation in TMXGenerator

### ISSUE THREAD

**Issue by rakkarage** [cocos2d/cocos2d-iphone-extensions#64]
//- (int) tileRotationForLayer:(NSString*)layerName X:(int)x Y:(int)y
//{
//  // If you had implemented rotated tiles then you would return degree rotation for the passed in tile coords on the passed layer.  We are not using (meaningful) rotation in this example.
//  return 0;
//}

when i comment this out to prevent default rotation (none) from being included in the file, it tries to compress the empty spaces/lines? and shows a warning

+[LFCGzipUtility gzipData:]: Compressed file from 4 KB to 0 KB
Error: Can't compress an empty or null NSData object.

**Comment by psineur** [comment]
Marked 0.2 Minor Defect.
Thanks!

@slycrel, any ideas how to fix this?
Thanks!

**Comment by slycrel** [comment]
I'll have a look, should be pretty easy to fix.
