### ISSUE TITLE
CCScrollLayer should restore blending functions

### ISSUE THREAD

**Issue by jan-ekholm** [cocos2d/cocos2d-iphone-extensions#67]
While using the CCScroillLayer class I noticed that my game had started to look very different from what it looked before. After some searching I found that the "visit" method of CCScrollLayer sets a custom blending function but did not restore it afterwards. I added a few lines below to query the blending functions and restore them.
- (void) visit
  {

...  
        // Set GL Values
        glEnable(GL_POINT_SMOOTH);
        GLboolean blendWasEnabled = glIsEnabled( GL_BLEND );
        glEnable(GL_BLEND);

```
    // save the old blending functions
    int blend_src;
    int blend_dst;
    glGetIntegerv( GL_BLEND_SRC, &blend_src );
    glGetIntegerv( GL_BLEND_DST, &blend_dst );

    glBlendFunc( GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA );
    glPointSize( 6.0 * CC_CONTENT_SCALE_FACTOR() );

    // Draw Gray Points
    glColor4ub(0x96,0x96,0x96,0xFF);
    ccDrawPoints( points, totalScreens );

    // Draw White Point for Selected Page
    glColor4ub(0xFF,0xFF,0xFF,0xFF);
    ccDrawPoint(points[currentScreen_]);

    // Restore GL Values
    glPointSize(1.0f);
    glDisable(GL_POINT_SMOOTH);
    if (! blendWasEnabled)
        glDisable(GL_BLEND);

    // always restore the blending functions too
    glBlendFunc( blend_src, blend_dst );
}
```

}

**Comment by psineur** [comment]
Thanks, merged in develop!
