### ISSUE TITLE
CCScrollLayer moveToPage

### ISSUE THREAD

**Issue by Jugon** [cocos2d/cocos2d-iphone-extensions#82]
moveToPage call moveToPageEnded twice

**Comment by psineur** [comment]
Can you provide additional info about this?
Where it get's called twice and why?

**Comment by Jugon** [comment]
My CCScrollLayer have one CCMenu on each layer, the CCMenuItem call a block that call moveToPage:(int)page

in my method delegate
- (void)scrollLayer:(CCScrollLayer *)sender scrolledToPageNumber:(int)page
  i execute an action on the CCMenuItem

**Comment by psineur** [comment]
Defect confirmed. Delegate method scrollLayer:scrolledToPageNumber: called twice in CCScrollLayerTest if moved to page with bottom menu.

Moved to 0.2
Labeled Minor Defect.

Thanks!

**Comment by Jugon** [comment]
ok, thanks to you
