### ISSUE TITLE
CCScrollLayer Pages Indicator

### ISSUE THREAD

**Issue by Jugon** [cocos2d/cocos2d-iphone-extensions#84]
Add a way to change the pages indicator... 
Maybe providing two ccsprite or colors to selected / unselected pages...

**Comment by sapsaldog** [comment]
I added two parameters, remain thing is just added two sprite and draw into layer

**Comment by psineur** [comment]
Merged. Thanks! 

Congrats on first Pull Request! =) 
:octocat:

**Comment by sapsaldog** [comment]
I cannot believe this.

I'll continue to pulling request this project,

I really appreciate you.

2011년 11월 7일 월요일에 Stepan Generalov님이 작성:
