### ISSUE TITLE
CCScrollLayer: Mac 32-Bit, LLVM 3.0 - synthesized property build error

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-iphone-extensions#88]
The following errors are issued in Mac 32-Bit builds with LLVM 3.0. 64-Bit build does not show these errors, nor do iOS Device and Simulator builds. Error occurs in downloadable extensions v0.2 release.

Synthesized property 'pagesIndicatorNormalColor' must either be named the same as a compatible ivar or must explicitly name an ivar
Synthesized property 'pagesIndicatorSelectedColor' must either be named the same as a compatible ivar or must explicitly name an ivar

The issue is because the @synthesize statement assigns an ivar name to the property:
@synthesize pagesIndicatorNormalColor = pagesIndicatorNormalColor_;
@synthesize pagesIndicatorSelectedColor = pagesIndicatorSelectedColor_;

This I believe is incompatible with automated ivar creation. The easiest fix is to add the ivars to class @interface:
    ccColor4B pagesIndicatorNormalColor_;
    ccColor4B pagesIndicatorSelectedColor_;

**Comment by psineur** [comment]
Thanks, closed in develop.
