### ISSUE TITLE
(Cocos2D 1.1) MutatedChildren in CCDirector is set to late.

### ISSUE THREAD

**Issue by sebas86** [cocos2d/cocos2d-iphone-extensions#92]
MutatedChildren variable schould be set on init. Now mutatedChildren is set to 0 only on drawScene, when some childs was created and added to scene with probably wrong mutatedChildren value.

In some random cases this cause problems with node ordering.

**Comment by psineur** [comment]
For what extension is this issue? I can't remember mutatedChildren there.
If you're talking about Cocos2D files (under cocos2d directory) - you need to open issue here: http://code.google.com/p/cocos2d-iphone/

**Comment by sebas86** [comment]
I'm sory, this bug schould be posted in other place (in Cocos2D-iphone, not Cocos2D-iphone-extensions).

**Comment by psineur** [comment]
No problem. Closed.
